# application-ncp.yml
spring:
  config:
    activate:
      on-profile: ncp

  jpa:
    hibernate:
      ddl-auto: update  # 운영 시에는 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# NCP Cloud DB for MySQL 설정
database:
  mysql:
    host: ${NCP_DB_HOST}
    port: ${NCP_DB_PORT:3306}
    name: ${NCP_DB_NAME}
    username: ${NCP_DB_USERNAME}
    password: ${NCP_DB_PASSWORD}

  hikari:
    maximum-pool-size: 20
    minimum-idle: 5
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

# NCP 특화 설정
ncp:

  # VPC 설정
  vpc:
    private-subnet: ${NCP_PRIVATE_SUBNET}
    security-group: ${NCP_SECURITY_GROUP}
