# application.yml
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    group:
      local:
        - mysql
      docker:
        - docker
      ncp:
        - ncp

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: none
    try-it-out-enabled: true

# Feign 클라이언트 설정
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 30000
        logger-level: full
  compression:
    request:
      enabled: true
    response:
      enabled: true

# 로깅 설정
logging:
  level:
    com.swen.news.global.client: DEBUG
    feign: DEBUG

external-api:
  naver:
    news:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
      base-url: "https://openapi.naver.com"

    hyperclova:
      api-key: ${NAVER_HYPERCLOVA_API_KEY}
      apigw-api-key: ${NCP_ACCESS_KEY}
      api-gateway-url: ${NAVER_HYPERCLOVA_API_GATEWAY_URL}
      request-id: ${NAVER_HYPERCLOVA_REQUEST_ID}

    clova-voice:
      url : ${CLOVA_VOICE_URL}
      client-id: ${CLOVA_VOICE_CLIENT_ID}
      client-secret: ${CLOVA_VOICE_CLIENT_SECRET}

ncp:
  region: ${NCP_REGION:KR}

  # Object Storage 설정 (음성 파일 저장용)
  object-storage:
    endpoint: ${NCP_OBJECT_STORAGE_ENDPOINT}
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
    bucket-name: ${NCP_BUCKET_NAME:obj-swen}