# application-mysql.yml
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    url: ${MYSQL_LOCAL_URL}
    driver-class-name: ${MYSQL_DRIVER_CLASS_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update  # 운영 시에는 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true